### PR TITLE
fix: handle missing transaction cookie with auth-state-aware response

### LINKED ISSUE #625: BadRequestError: checks.state argument is missing when routing between pages using browser's back button
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have multiple apps using the same domain with the same login system (Cognito). When navigating directly to a page, there are no issues. However, if I navigate to the first page, then go to the second page, and finally click the browser's back button to return to the first page, I always encounter a BadRequestError.
```
BadRequestError: checks.state argument is missing
    at ResponseContext.callback (/home/node_modules/express-openid-connect/lib/context.js:354:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It only happens on v2 express-openid-connect, but not on v1. 
App using v2 is able to return to app using v1 without issue using browser's back button. Somehow it only happens in v2.
Is it the desired behavior or am I overlooking something? Thank you for your time.

### Reproduction

1. Login to the portal
2. Route to the first page
3. Route to the second page
4. Click browser's back button to return to the first page.
5. Error shows up

One of the apps setup:
```
server.use(
        auth({
            authRequired: true,
            issuerBaseURL: `https://cognito-idp.us-east-1.amazonaws.com/${process.env.USER_POOL_ID}`,
            baseURL,
            clientID: `${process.env.COGNITO_CLIENT_ID}`,
            clientSecret: `${process.env.COGNITO_CLIENT_SECRET}`,
            secret,
            authorizationParams: {
                response_type: "code",
                scope: "openid profile",
            },
            routes: {
                postLogoutRedirect: `https://${process.env.COGNITO_USER_POOL_DOMAIN}/logout?client_id=${process.env.COGNITO_CLIENT_ID}&logout_uri=${baseUrl}`,
            },
            afterCallback: async function (req, res, session, decodedState) {
                try {
                    return session;
                } catch (err) {
                    console.error(
                        "There was a problem after auth callback: ",
                        err
                    );
                    return session;
                }
            },
        })
    );
```

### Additional context

_No response_

### express-openid-connect version

2.17.1

### Express version

4.18.2

### Node.js version

16

### LINKED ISSUE #627: Improve the "checks.state argument is missing" error message
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

There are a lot of [requests for help](https://www.google.com/search?q=%22checks.state+argument+is+missing%22) with this error message, on multiple community sites.

The current error message probably made sense to whoever was writing the function that was invoked with a "checks" object that was missing a "state" property, but it's meaningless to the those of us who have to troubleshoot such errors, because _we didn't call that function._ 

We didn't call any function with parameters that even looks remotely like it needs a "state" parameter.

In fact we even have a distraction - my only guess at the time was that this message was related to not setting the "state" property of callbackParams.tokenEndpointParams - because it's named "state" and it was passed to the last function that I called before getting this error... But I continued to get the same error when callbackParams.tokenEndpointParams.state was clearly NOT missing.

### Describe the ideal solution

Change the error message to "checks.state is not present in the auth_verification cookie"

...since that's what [we get told to investigate](https://github.com/auth0/express-openid-connect/issues/512#issuecomment-1749173040) when they ask for help with this message. 

### Alternatives and current workarounds

1. ask for help
1. wait for a response
1. someone posts a response

We could skip all of those steps and just put that clue right into the error message.

### Additional context

I'd submit a PR to fix this, but I can't figure out where the phrase "argument is missing" is coming from. 

I searched the repo, but only found results in test cases.

### PR DESCRIPTION
**Pull request by aks96**
#### Problem

When the `auth_verification` transaction cookie is absent at the callback route, the SDK threw:

`BadRequestError: checks.state argument is missing`

This message is an internal `openid-client` detail, it gives developers no indication of why the cookie is missing or how to fix it. The same opaque error surfaced across three distinct root causes:

1. Back-button / stale callback — user completed login, transaction cookie was consumed, then the browser re-fired the same /callback URL (e.g pressing back).
2. Dropped SameSite=None cookie — browser rejected the cookie because the origin is HTTP, not HTTPS (Safari ITP, privacy mode, Chrome on non-HTTPS)
3. legacySameSiteCookie=false + buggy browser — primary cookie blocked on cross-site return, no fallback cookie set
4. Multi-app cookie collision — two apps on the same domain with the same `transactionCookie.name` and `cookie.path`, one app's login overwrote the other's cookie

#### Fix

After `getOnce()` returns undefined, the handler now branches on authentication state:

1. Authenticated user → silent redirect to baseURL
The transaction cookie was legitimately consumed on the first successful callback. The browser re-firing the same URL is a benign back-button navigation. The user is already logged in — redirect them home with no error.

2. Unauthenticated user → descriptive 400 error
The cookie is missing for a user who hasn't established a session yet. The error message names the cookie, lists all four root causes, and suggests fix for each — replacing the cryptic `checks.state argument is missing` with actionable developer guidance.

### Testing
1. Verify all existing and new tests pass.
2. Stale Callback - Authenticated User.
3. Missing Cookie - Unauthenticated User.
4. Multi-App Cookie Collision.

### CODE REVIEW

File: lib/context.js [hunk 1]
```diff
@@ -380,6 +380,15 @@ class ResponseContext {
...
 
+        // Handle stale callback (e.g., user pressed back button after successful login)
+        // If no auth verification cookie and user is already authenticated, redirect to baseURL
+        if (!authVerification && req.oidc.isAuthenticated()) {
+          debug(
+            'stale callback detected (no auth verification cookie), user already authenticated, redirecting to baseURL',
+          );
+          return res.redirect(config.baseURL);
+        }
+
```
Comment (cschetan77) [inline lib/context.js]: What happens if stale /callback is replayed and user is not authenticated as well (or the session cookie is genuinely lost somehow, maybe through a cookie collision that we've seen) ?
Do you suggest, it's better to redirect the user to /login route to start a fresh login in that scenario !
Something like - 

```suggestion
  if (!authVerification) {
    // Stale or replayed callback — transaction cookie already consumed.
    if (req.oidc.isAuthenticated()) {
    debug(
            'stale callback detected (no auth verification cookie), user already authenticated, redirecting to baseURL',
          );
      // Back-button scenario: user is already logged in, just send them home.
      return res.redirect(config.baseURL);
    } else {
      // Cookie was genuinely lost (e.g. cookie collision). Start a fresh login.
      return res.redirect(config.routes.login || '/login');
    }
  }
```

Comment (cschetan77) [reply lib/context.js]: Or on second thought, instead of the SDK making assumptions, just redirecting to config.baseURL unconditionally makes more sense. 
So, if a stale /callback is replayed in any scenario, whether authenticated or not, let's redirect to config.baseUURL. What do you suggest. 
```javascript
if (!authVerification) {
          debug(
            'stale callback detected (no auth verification cookie) redirecting to baseURL',
          );
          return res.redirect(config.baseURL);
        }
```

Comment (aks96) [reply lib/context.js]: Yes, that's exactly what the current implementation does,  it redirects to baseURL unconditionally when no auth verification cookie is found, regardless of authentication status.

- If authenticated user lands to baseURL
- If not authenticated user lands on baseURL then middleware will redirect to login.

Comment (cschetan77) [reply lib/context.js]: Maybe I missed something, but with the current check - `if (!authVerification && req.oidc.isAuthenticated())`, if it's a stale request and the user is not authenticated, won't the execution move forward past this condition and fail again with same error `BadRequestError: checks.state argument is missing`.

**Review by cschetan77 — DISMISSED** [review]

File: lib/context.js [hunk 2]
```diff
@@ -481,6 +380,17 @@ class ResponseContext {
           res,
         );
 
+        // Handle stale/replayed callback (e.g., user pressed back button, or cookie was lost)
+        // If no auth verification cookie, redirect to baseURL instead of throwing an error.
+        // If user is authenticated, they'll land on the home page.
+        // If not authenticated, authRequired middleware will redirect to login if needed.
+        if (!authVerification) {
```
Comment (nandan-bhat) [inline lib/context.js:484]: Should we only redirect here when the user is already signed in ? 

If the callback comes back without the transaction cookie because the browser dropped it, someone opened `/callback` directly, or another app overwrote the cookie, this looks like a real login failure, not a stale back-button replay.

Could this turn a `400` into a silent redirect or even a login loop when `authRequired` is true ?

File: lib/context.js
Comment (nandan-bhat) [inline lib/context.js:478]: Can we tell the difference between a missing transaction cookie and an invalid one here ?

`transient.getOnce()` returns no value in both cases, so this redirect may also hide bad or unverifiable cookies. Should invalid cookies still fail with an error instead of being treated as a stale callback ?

File: index.d.ts [hunk 3]
```diff
@@ -924,7 +848,10 @@ interface CookieConfigParams {
 
   /**
    * Path for the cookie.
-   * Passed to the [Response cookie](https://expressjs.com/en/api.html#res.cookie) as `path`
+   * Passed to the [Response cookie](https://expressjs.com/en/api.html#res.cookie) as `path`.
+   *
+   * To prevent cookie collision when multiple apps are hosted on the same domain
```
Comment (nandan-bhat) [inline index.d.ts:929]: Should we also add this guidance to the `README` or `FAQ` ?

This note is helpful here, but the public docs still mostly talk about generic `"invalid state"` errors and do not explain cookie collisions or using `session.cookie.path` / `transactionCookie.name` to isolate apps on the same domain.

File: lib/context.js (hunk 2 above)
Comment (cschetan77) [reply lib/context.js:484]: I've updated the fix, we now branch on authentication state:

Authenticated + no authVerification cookie -> redirect to baseURL. The transaction cookie was legitimately consumed on the first successful callback. The browser re-firing the same /callback URL is a benign back-button replay. The user is already logged in, so sending them home makes sense.

Unauthenticated + no authVerification cookie -> 400 with a descriptive error message. This covers all the real failure cases you listed — browser dropped the cookie, direct navigation to /callback, multi-app collision. These are genuine login failures and deserve an error, not a silent redirect. The message names the cookie and lists actionable fixes for each root cause, replacing the previous cryptic `checks.state argument is missing`.

So the silent redirect and login loop concern no longer applies — unauthenticated users with no authVerification always get an error regardless of authRequired.

PR description updated as well.

File: lib/context.js
Comment (cschetan77) [reply lib/context.js:478]: No, with current SDK behavior, we can't differentiate between a missing and an invalid authVerification cookie.

The earlier behavior was:
When `getOnce()` returned undefined for any reason — absent cookie, tampered cookie, multi-app collision, execution fell straight through to [client.callback()](https://github.com/auth0/express-openid-connect/blob/92cc86e896a58521acfa50a5c66a4b530ba663a8/lib/context.js#L488) with `checks = {}`. The openid-client library then saw `checks.state` was undefined and threw: `BadRequestError: checks.state argument is missing  (HTTP 400)`

With updated commit [3232e5a](https://github.com/auth0/express-openid-connect/pull/797/commits/3232e5ac4b01d6a82f6b57e2ceaedb1f69922ba3), the flow branches out - 
1. For the unauthenticated branch - Both absent and invalid cookies land in the throw new Error(...) path. The user gets a 400 either way.
2. For the authenticated branch - a tampered cookie also triggers a redirect to baseURL. But that means:
   - An authenticated user has a tampered auth_verification cookie in their browser
   - The auth code exchange is silently aborted and they're sent home
   - They're already logged in, so no harm done
 This is safer than throwing an error - it stops the exchange without leaking information.

File: index.d.ts (hunk 3 above)
Comment (cschetan77) [reply index.d.ts:929]: Yes, I agree, we should add this guidance. 
Updated both -
1. `FAQ.md` has a new entry: `I'm getting "auth_verification" cookie not found - login fails intermittently or only on certain browsers`. It covers all four root causes that produce this error (direct navigation to /callback, HTTP origin dropping the cookie, legacySameSiteCookie: false with a buggy browser, and multi-app cookie collision), each with a diagnosis and a fix. The collision scenario includes a step-by-step flow showing exactly how App 2's cookie overwrites App 1's.

2. `README.md` has a new `Deploying Multiple Apps on the Same Domain` section, a working side-by-side config example with all three isolation knobs (session.name, session.cookie.path, transactionCookie.name), and a link to the FAQ entry for the full explanation.

**Review by nandan-bhat — APPROVED** [review]

**Comment by natewaddoups** [comment]
Thank you @cschetan77 !
